<a href="https://colab.research.google.com/github/janani-pb/IDRA-assignment/blob/main/IDRA_DAY_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("=" * 60)
print("NUMPY PRACTICE NOTEBOOK - DAY 6")
print("=" * 60)

print("\n1. NUMPY VERSION")
print("NumPy Version:", np.__version__)

print("\n2. 1D ARRAY")
arr_1d = np.array([10, 20, 30, 40, 50])
print("Array:", arr_1d)
print("Dimensions:", arr_1d.ndim)
print("Shape:", arr_1d.shape)
print("Data Type:", arr_1d.dtype)

print("\n3. 2D ARRAY")
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr_2d)
print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Data Type:", arr_2d.dtype)

print("\n4. 3D ARRAY")
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(arr_3d)
print("Dimensions:", arr_3d.ndim)
print("Shape:", arr_3d.shape)
print("Data Type:", arr_3d.dtype)

print("\n5. ARRAY PROPERTIES")
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print("Array:")
print(arr)
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

print("\n6. INDEXING")
numbers = np.array([10, 20, 30, 40, 50])
print("Array:", numbers)
print("First Element:", numbers[0])
print("Third Element:", numbers[2])
print("Last Element:", numbers[-1])

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("Element at Row 1 Column 2:", matrix[0, 1])
print("Element at Row 2 Column 3:", matrix[1, 2])
print("Last Row First Column:", matrix[-1, 0])

print("\n7. SLICING")
numbers = np.array([10, 20, 30, 40, 50, 60])
print("First Three Elements:", numbers[:3])
print("From Index 2:", numbers[2:])
print("Index 1 to 4:", numbers[1:5])
print("Every Second Element:", numbers[::2])

print("First Two Rows:")
print(matrix[:2])
print("First Two Columns:")
print(matrix[:, :2])

print("\n8. RESHAPING")
arr = np.arange(1, 13)
print("Original Array:", arr)
reshaped = arr.reshape(3, 4)
print("Reshaped Array:")
print(reshaped)

print("\n9. ZEROS")
zero_array = np.zeros((3, 4))
print(zero_array)

print("\n10. ONES")
one_array = np.ones((2, 3))
print(one_array)

print("\n11. ARANGE")
arr1 = np.arange(1, 11)
print("1 to 10:", arr1)

arr2 = np.arange(0, 20, 2)
print("0 to 18 with Step 2:", arr2)

print("\n12. LINSPACE")
arr3 = np.linspace(0, 10, 6)
print("Six Values from 0 to 10:", arr3)

print("\n13. MATHEMATICAL OPERATIONS")
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

print("\n14. MATHEMATICAL FUNCTIONS")
numbers = np.array([1, 4, 9, 16, 25])
print("Numbers:", numbers)
print("Square Root:", np.sqrt(numbers))
print("Square:", np.square(numbers))

print("\n15. VECTORIZED OPERATIONS")
marks = np.array([50, 60, 70, 80, 90])
print("Original Marks:", marks)
print("Marks After Adding 5:", marks + 5)

numbers = np.array([1, 2, 3, 4, 5])
print("Numbers * 2 + 10:", numbers * 2 + 10)

print("\n16. BOOLEAN MASKING")
marks = np.array([45, 67, 89, 32, 76, 90, 55])
print("Marks:", marks)
print("Boolean Mask:", marks >= 60)
print("Marks Greater Than or Equal to 60:", marks[marks >= 60])

numbers = np.array([10, 25, 30, 45, 50, 65, 70])
print("Values Greater Than 40:", numbers[numbers > 40])

print("\n17. BROADCASTING")
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])

print("Original Marks:")
print(marks)

print("After Adding 5:")
print(marks + 5)

a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([1, 2, 3])

print("Broadcasting Result:")
print(a + b)

print("\n18. AGGREGATE FUNCTIONS")
data = np.array([10, 20, 30, 40, 50])

print("Data:", data)
print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

print("\n19. AGGREGATE FUNCTIONS ON 2D ARRAY")
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [90, 95, 88]
])

print("Marks:")
print(marks)

print("Total:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Median:", np.median(marks))
print("Column-wise Sum:", np.sum(marks, axis=0))
print("Row-wise Sum:", np.sum(marks, axis=1))

print("\n20. SORTING")
numbers = np.array([50, 20, 80, 10, 40])
print("Original Array:", numbers)
print("Sorted Array:", np.sort(numbers))
print("Index of Minimum:", np.argmin(numbers))
print("Index of Maximum:", np.argmax(numbers))

print("\n21. PRACTICAL STUDENT MARKS ANALYSIS")
marks = np.array([78, 85, 62, 90, 55, 73, 88, 95, 68, 81])

print("Student Marks:", marks)
print("Total Marks:", np.sum(marks))
print("Average Marks:", np.mean(marks))
print("Minimum Marks:", np.min(marks))
print("Maximum Marks:", np.max(marks))
print("Median Marks:", np.median(marks))
print("Students Scoring 75 or Above:", marks[marks >= 75])
print("Students Scoring Below 50:", marks[marks < 50])



NUMPY PRACTICE NOTEBOOK - DAY 6

1. NUMPY VERSION
NumPy Version: 2.0.2

2. 1D ARRAY
Array: [10 20 30 40 50]
Dimensions: 1
Shape: (5,)
Data Type: int64

3. 2D ARRAY
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimensions: 2
Shape: (3, 3)
Data Type: int64

4. 3D ARRAY
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensions: 3
Shape: (2, 2, 3)
Data Type: int64

5. ARRAY PROPERTIES
Array:
[[10 20 30]
 [40 50 60]]
Dimensions: 2
Shape: (2, 3)
Size: 6
Data Type: int64

6. INDEXING
Array: [10 20 30 40 50]
First Element: 10
Third Element: 30
Last Element: 50
Element at Row 1 Column 2: 20
Element at Row 2 Column 3: 60
Last Row First Column: 70

7. SLICING
First Three Elements: [10 20 30]
From Index 2: [30 40 50 60]
Index 1 to 4: [20 30 40 50]
Every Second Element: [10 30 50]
First Two Rows:
[[10 20 30]
 [40 50 60]]
First Two Columns:
[[10 20]
 [40 50]
 [70 80]]

8. RESHAPING
Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

9.